[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ambergris"
version = "0.1.0"
description = "Utilities for running Docker images with Python"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Sophie Paul" }
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License"
]
dependencies = [
    "docker==7.1.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "pytest-mock>=3.15.1",
    "black>=24.0.0",
    "mypy>=1.8.0",
    "types-docker"
]

[tool.hatch.version]
path = "src/ambergris/__about__.py"

[tool.black]
line-length = 88
target-version = ['py312']

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]